import { contextBridge,ipcRenderer } from 'electron';
import type { Bridge } from '../shared/types';
let workspaceScope:string|undefined,pendingScope:string|undefined;
const invokeFor=async(scope:string|undefined,channel:string,...args:unknown[])=>{const response=await ipcRenderer.invoke('owl:'+channel,{scope},...args);if(!response.ok)throw new Error(response.error);if(channel==='snapshot'){pendingScope=response.scope;if(workspaceScope!==pendingScope)workspaceScope=undefined;}return response.value;};
function createBridge(boundScope?:string):Bridge {
 const invoke=(channel:string,...args:unknown[])=>invokeFor(boundScope??workspaceScope,channel,...args);
 return {forWorkspace:scope=>createBridge(scope),activateWorkspace:revision=>{if(revision===pendingScope)workspaceScope=revision;},resolveSync:()=>invoke('resolveSync'),openAppMenu:(name,x,y)=>invoke('openAppMenu',name,x,y),systemTimeFormat:()=>invoke('systemTimeFormat'),loginGoogle:()=>invoke('loginGoogle'),cancelGoogleLogin:()=>invoke('cancelGoogleLogin'),snapshot:()=>invoke('snapshot'),saveDeck:x=>invoke('saveDeck',x),deleteDeck:id=>invoke('deleteDeck',id),addWords:(id,rows)=>invoke('addWords',id,rows),editWord:(id,row)=>invoke('editWord',id,row),deleteWord:id=>invoke('deleteWord',id),saveSettings:x=>invoke('saveSettings',x),queue:id=>invoke('queue',id),previews:id=>invoke('previews',id),reviewSession:active=>invoke('reviewSession',active),review:(id,g,a)=>invoke('review',id,g,a),importFile:mode=>invoke('importFile',mode),parse:(text,mode)=>invoke('parse',text,mode),exportDeck:id=>invoke('exportDeck',id),backup:()=>invoke('backup'),restore:()=>invoke('restore'),account:()=>invoke('account'),sync:()=>invoke('sync'),login:(e,p)=>invoke('login',e,p),logout:()=>invoke('logout'),deleteAccount:()=>invoke('deleteAccount'),refreshEntitlement:()=>invoke('refreshEntitlement'),translate:(w,n,l)=>invoke('translate',w,n,l),catalog:q=>invoke('catalog',q),importCatalog:d=>invoke('importCatalog',d),publish:id=>invoke('publish',id),unpublish:id=>invoke('unpublish',id),openSubscriptionManagement:()=>invoke('openSubscriptionManagement')};
}
contextBridge.exposeInMainWorld('owl',createBridge());
