import { _electron as electron } from 'playwright';
import { createCanvas } from '@napi-rs/canvas';
import { mkdirSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const dir=resolve('test-results/imports');mkdirSync(dir,{recursive:true});
const canvas=createCanvas(1000,300),ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,1000,300);ctx.fillStyle='black';ctx.font='54px Arial';ctx.fillText('hello - privet',60,100);ctx.fillText('world - mir',60,200);writeFileSync(resolve(dir,'words.png'),canvas.toBuffer('image/png'));
writeFileSync(resolve(dir,'words.csv'),'word,translation\n"hello","привет"\nworld,мир');
function pdf(objects,path){let bytes=Buffer.from('%PDF-1.4\n'),offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(bytes.length);bytes=Buffer.concat([bytes,Buffer.from(`${i+1} 0 obj\n`),objects[i],Buffer.from('\nendobj\n')]);}const xref=bytes.length;bytes=Buffer.concat([bytes,Buffer.from(`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`)]);writeFileSync(path,bytes);}
const b=x=>Buffer.from(x),stream=x=>Buffer.concat([b(`<< /Length ${x.length} >>\nstream\n`),x,b('\nendstream')]);
pdf([b('<< /Type /Catalog /Pages 2 0 R >>'),b('<< /Type /Pages /Kids [3 0 R] /Count 1 >>'),b('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 400] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>'),b('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'),stream(b('BT /F1 24 Tf 50 300 Td (hello - privet) Tj 0 -40 Td (world - mir) Tj ET'))],resolve(dir,'text.pdf'));
const jpeg=canvas.toBuffer('image/jpeg');pdf([b('<< /Type /Catalog /Pages 2 0 R >>'),b('<< /Type /Pages /Kids [3 0 R] /Count 1 >>'),b('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 500 150] /Resources << /XObject << /Im1 4 0 R >> >> /Contents 5 0 R >>'),Buffer.concat([b(`<< /Type /XObject /Subtype /Image /Width 1000 /Height 300 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,b('\nendstream')]),stream(b('q 500 0 0 150 0 0 cm /Im1 Do Q'))],resolve(dir,'scan.pdf'));
const data=resolve('test-results/import-profile');mkdirSync(data,{recursive:true});const app=await electron.launch({executablePath:process.env.OWL_TEST_EXECUTABLE,args:process.env.OWL_TEST_EXECUTABLE?[]:['.'],env:{...process.env,OWL_TEST_DATA_DIR:data}});
try{const page=await app.firstWindow();await page.waitForFunction(()=>!!window.owl);for(const filename of ['words.csv','text.pdf','words.png','scan.pdf']){await app.evaluate(({dialog},path)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path]});},resolve(dir,filename));const result=await page.evaluate(()=>window.owl.importFile('auto'));if(!result.drafts.some(x=>x.word.toLowerCase().includes('hello')))throw new Error(`No expected word from ${filename}: ${JSON.stringify(result)}`);console.log(`PASS ${filename}: ${result.drafts.length} drafts`);}}finally{await app.close();}
