import { WorkspaceBridgeProvider } from './WorkspaceBridge';
import { useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState } from 'react';
import { ArrowLeft,ArrowRight,BookOpen,CalendarDays,Check,ChevronDown,ChevronRight,Flame,FolderOpen,GraduationCap,LayoutGrid,LogIn,MoreHorizontal,Plus,Search,Settings as SettingsIcon,Sparkles,Target,Trash2,X,Download,Upload,PenLine,CloudOff,Crown,CircleHelp } from 'lucide-react';
import type { AccountState,Deck,Draft,Snapshot,Word } from '../shared/types';
import { languageName } from '../shared/types';
import { Owl,Empty,Modal,Speak,LanguageSelect,errorMessage } from './components';
import CreateSet from './CreateSet';
import Review from './Review';
import Profile from './Profile';
import Settings from './Settings';
import Library from './Library';
import Help from './Help';
type Page='learn'|'sets'|'library'|'add'|'create'|'profile'|'settings'|'help';
type ReturnPage={page:Page;query:string;selected:string;editDeck?:Deck};
const hasBack=(page:Page)=>page==='help'||page==='create'||page==='add';
const navigation=[['learn',GraduationCap,'Learn'],['sets',FolderOpen,'My sets'],['library',BookOpen,'Library']] as const;
export default function App(){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[account,setAccount]=useState<AccountState>({profile:null,entitlement:null}),[page,setPage]=useState<Page>('learn'),[query,setQuery]=useState(''),[savedSelection,setSelected]=useState(''),[due,setDue]=useState(0),[review,setReview]=useState(false),[editDeck,setEditDeck]=useState<Deck|undefined>(),[editWord,setEditWord]=useState<Word|null>(null),[deleteTarget,setDeleteTarget]=useState<{kind:'deck'|'word';id:string;name:string}|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[menu,setMenu]=useState(''),[expanded,setExpanded]=useState('');const searchRef=useRef<HTMLInputElement>(null);const returnPages=useRef<ReturnPage[]>([]);const workspace=useRef<string|null>(null);const reloadGeneration=useRef(0);
 const owl=useMemo(()=>snapshot?window.owl.forWorkspace(snapshot.scopeRevision):window.owl,[snapshot?.scopeRevision]);
 const selected=snapshot?.decks.length===1?snapshot.decks[0].id:savedSelection;
 useEffect(()=>{if(!snapshot)return;setSelected(current=>snapshot.decks.length===1?snapshot.decks[0].id:snapshot.decks.some(deck=>deck.id===current)?current:'');},[snapshot]);
 useEffect(()=>{if(!snapshot)return;try{localStorage.setItem(`owl.selectedCollection.${snapshot.workspaceId}`,selected);}catch{}},[selected,snapshot]);
 const notify=useCallback((message:string)=>{if(workspace.current===snapshot?.scopeRevision)setNotice(message);},[snapshot?.scopeRevision]);
 const reload=useCallback(async()=>{
  const generation=++reloadGeneration.current;
  const data=await window.owl.snapshot();
  if(generation!==reloadGeneration.current)return;
  if(workspace.current!==data.scopeRevision){
   const wasOpen=workspace.current!==null;workspace.current=data.scopeRevision;
   let selection='';try{selection=localStorage.getItem('owl.selectedCollection.'+data.workspaceId)??'';}catch{}
   setSelected(selection);setQuery('');setReview(false);setEditDeck(undefined);setEditWord(null);setDeleteTarget(null);setMenu('');setExpanded('');setError('');setNotice('');setBusy(false);returnPages.current=[];
   if(wasOpen)setPage(current=>current==='profile'?'profile':'learn');
   speechSynthesis?.cancel();
  }
  setSnapshot(data);setAccount(data.account??{profile:null,entitlement:null});setDue(data.queueCount??0);
 },[]);
 useLayoutEffect(()=>{if(snapshot)window.owl.activateWorkspace(snapshot.scopeRevision);},[snapshot?.scopeRevision]);
 useEffect(()=>{if(!window.owl){setError('Open Owl AI using the Windows application. This interface requires its secure desktop connection.');return;}reload().catch(e=>setError(errorMessage(e)));speechSynthesis?.getVoices();},[reload]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>{if(!window.owl)return;const refresh=()=>{void reload().catch(()=>{});};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[reload]);
 useEffect(()=>{if(!account.profile)return;let active=true;const refresh=()=>{void owl.refreshEntitlement().then(()=>{if(active)void reload().catch(()=>{});}).catch(()=>{if(active)void reload().catch(()=>{});});};refresh();const timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);};},[account.profile?.id,reload,owl]);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.ctrlKey&&event.key.toLowerCase()==='f'){event.preventDefault();returnPages.current=[];setPage('learn');requestAnimationFrame(()=>searchRef.current?.focus());}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{if(!snapshot)return;const media=matchMedia('(prefers-color-scheme: dark)');const apply=()=>{document.documentElement.dataset.theme=snapshot.settings.theme==='system'?(media.matches?'dark':'light'):snapshot.settings.theme;document.documentElement.dataset.accent=snapshot.settings.accent;document.documentElement.dataset.darkAccent=snapshot.settings.darkAccent;};apply();media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply);},[snapshot?.settings.theme,snapshot?.settings.accent,snapshot?.settings.darkAccent]);
 const run=async(fn:()=>Promise<void>)=>{const scope=workspace.current;setBusy(true);setError('');try{await fn();await reload();}catch(e){if(scope===workspace.current)setError(errorMessage(e));}finally{if(scope===workspace.current)setBusy(false);}};
 useEffect(()=>{window.scrollTo(0,0);},[page]);
 const go=(target:Page,deck?:Deck)=>{
  if(target===page)return;
  if(hasBack(target))returnPages.current.push({page,query,selected,editDeck});else returnPages.current=[];
  setPage(target);setQuery('');setMenu('');setError('');if(target==='create'||target==='add')setEditDeck(deck);
 };
 const addCards=(deck:Deck)=>go('add',deck);
 const goBack=()=>{const previous=returnPages.current.pop();setPage(previous?.page??'learn');setQuery(previous?.query??'');setSelected(previous?.selected??'');setEditDeck(previous?.editDeck);setMenu('');setError('');};
 if(!snapshot)return <div className="boot"><Owl size={70}/><h1>Owl AI</h1><p>{error||'Opening your learning space…'}</p>{error&&window.owl&&<button className="button" onClick={()=>reload().catch(e=>setError(errorMessage(e)))}>Try again</button>}</div>;
 const {decks,words,settings}=snapshot,selectedDeck=decks.find(x=>x.id===selected),filtered=words.filter(x=>(!selected||x.deckId===selected)&&(!query||[x.word,x.translation,x.notes].some(s=>s?.toLowerCase().includes(query.toLowerCase()))));
 const titles:Record<Page,[string,string]>={learn:['Your learning space','A little progress, every day.'],sets:['My flashcard sets','Everything you’re curious about, together.'],library:['Explore the library','Find something worth remembering.'],add:['Add cards',editDeck?.name??'Choose a collection for your words.'],create:[editDeck?'Edit flashcard set':'Create a flashcard set','Turn everyday discoveries into lasting knowledge.'],profile:['Account & Premium','A shared subscription. A familiar experience.'],settings:['Your preferences','A learning routine that feels like you.'],help:['Help','A simple guide to cards, practice, and Premium.']};
 // Keep authentication feedback through failed attempts; real account changes still reset the profile.
 const pageKey=page==='profile'?'profile:'+snapshot.workspaceId:snapshot.scopeRevision;
 const premium=['premium','trial','grace'].includes(account.entitlement?.status??'');
 return <WorkspaceBridgeProvider bridge={owl}><div className="app-shell"><aside className="sidebar"><button className="brand" onClick={()=>go('learn')}><Owl size={38}/><span>owl<span className="brand-ai">ai</span><small>WORDS THAT STAY.</small></span></button><span className="nav-label">YOUR SPACE</span><nav>{navigation.map(([target,Icon,label])=><button key={target} className={`nav-item ${page===target?'active':''}`} onClick={()=>go(target)}><Icon size={20}/><span>{label}</span>{target==='learn'&&due>0&&<span className="nav-count">{due}</span>}</button>)}</nav><button className="create-nav" onClick={()=>go('create')}><Plus size={20}/> Create a set</button><div className="sidebar-divider"/><span className="nav-label">YOUR COLLECTIONS <span>{decks.length}</span></span><div className="sidebar-sets">{decks.slice(0,8).map((deck,i)=><button key={deck.id} className={`sidebar-set ${selected===deck.id&&page==='learn'?'chosen':''}`} onClick={()=>{go('learn');setSelected(deck.id);}}><span className={`set-dot dot-${i%4}`}/><span>{deck.name}</span><small>{words.filter(x=>x.deckId===deck.id).length}</small></button>)}{!decks.length&&<p className="sidebar-empty">Your first collection<br/>starts with one word.</p>}</div><div className="sidebar-bottom"><div className="premium-nudge"><span className="premium-mini"><Sparkles size={16}/>{premium?'Your Premium travels with you':'One curious mind. Every screen.'}</span><p>{premium?'Enjoy Owl AI on iPhone and Windows.':'Bring your iPhone Premium to Windows.'}</p><button onClick={()=>go('profile')}>{premium?'View subscription':'Discover Premium'} <ArrowRight size={15}/></button></div><button className={`nav-item ${page==='settings'?'active':''}`} onClick={()=>go('settings')}><SettingsIcon size={19}/><span>Settings</span></button><button className="account-nav" onClick={()=>go('profile')}><div className="avatar">{account.profile?.email?.charAt(0).toUpperCase()??<LogIn size={18}/>}</div><span>{account.profile?.email?.split('@')[0]??'Make yourself at home'}<small>{account.profile?'Your Owl AI account':'Sign in to connect'}</small></span><ChevronRight size={16}/></button></div></aside>
 <main className="main"><div key={pageKey} className={`page-content ${page==='learn'?'learn-page':''}`}><header className="page-heading"><div className="page-heading-leading">{hasBack(page)&&<button className="back-button" onClick={goBack}><ArrowLeft size={17}/> Back</button>}<div><h1>{page==='learn'?'Learn':titles[page][0]}</h1><p>{titles[page][1]}</p></div></div><div className="heading-actions">{(page==='learn'||page==='sets')&&<button className="button" onClick={()=>go('create')}><Plus size={16}/> Create a set</button>}<button className="icon-button" aria-label="Preferences" title="Preferences" onClick={()=>go('settings')}><SettingsIcon size={18}/></button><button className="help-button" aria-label="Help" aria-current={page==='help'?'page':undefined} onClick={()=>go('help')}><CircleHelp size={17}/><span>Help</span></button><button className="avatar small-avatar" aria-label="Profile" title="Profile" onClick={()=>go('profile')}>{account.profile?.email?.charAt(0).toUpperCase()??'O'}</button></div></header>{error&&<div className="error global-error" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 {page==='learn'&&<><div className="stats-grid"><Stat Icon={BookOpen} label="Words collected" value={words.length} detail="A growing world of vocabulary" color="purple"/><Stat Icon={Target} label="Ready to review" value={due} detail="A little practice, a lasting memory" color="orange"/><Stat Icon={Check} label="Practiced today" value={snapshot.reviewedToday} detail="Every repetition counts" color="green"/><Stat Icon={Flame} label="Day streak" value={snapshot.streak} detail={snapshot.streak?'Keep your momentum going':'Your next habit starts today'} color="pink"/></div>
 <section className="practice-bar" aria-label="Daily practice"><div className="practice-summary"><span className="practice-icon"><GraduationCap size={24}/></span><div><h2>{due?'Ready for a little practice?':'Make room for a new word.'}</h2><p>{due?`${due} cards ready · pick up where you left off.`:'Add a few words to start your next session.'}</p></div></div><button className="button" onClick={()=>due?setReview(true):go('create')}>{due?'Start today’s practice':'Create your first cards'}<ArrowRight size={17}/></button></section>
 <section className="collections-section" aria-label="Your collections"><div className="section-line"><h2>Your collections <span className="count">{decks.length}</span></h2><div className="collection-actions"><button className="text-button" onClick={()=>go('sets')}>View all sets <ArrowRight size={16}/></button><button className="button secondary" onClick={()=>go('create')}><Plus size={16}/> Create a set</button></div></div>{decks.length>0&&<div className="collection-strip">{decks.slice(0,3).map(deck=><CollectionTile key={deck.id} deck={deck} count={words.filter(x=>x.deckId===deck.id).length} selected={selected===deck.id} onClick={()=>setSelected(selected===deck.id?'':deck.id)}/>)}</div>}</section>
 <div className="word-section"><div className="section-line"><h2>{selectedDeck?.name??'Your vocabulary'} <span className="count">{filtered.length}</span></h2><div className="word-tools">{selectedDeck&&<button className="button secondary" onClick={()=>addCards(selectedDeck)}><Plus size={16}/> Add cards</button>}<select aria-label="Filter set" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">All sets</option>{decks.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><div className="search-field"><Search size={16}/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a word…"/><kbd>Ctrl F</kbd></div></div></div>{filtered.length?<div className="word-list word-card-grid">{filtered.map(word=>{const deck=decks.find(x=>x.id===word.deckId),card=settings.direction==='forward'?word.card:word.reverse;return <div className="word-row-wrap word-mini-card" key={word.id}><div className="word-row"><div className="word-primary"><button className="word-expand" aria-expanded={expanded===word.id} onClick={()=>setExpanded(expanded===word.id?'':word.id)}><strong>{word.word}</strong><span>{word.translation||'Translation needed'}</span></button><Speak word={word.word} language={word.learningLanguage??deck?.learningLanguage??settings.learningLanguage} onError={notify}/></div><span className="set-tag" title={deck?.name}><FolderOpen size={13}/>{deck?.name}</span><span className={`review-date ${card.state===0?'new':''}`}>{card.state===0?'New word':new Date(card.due)<new Date()?'Ready now':new Date(card.due).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><div className="word-actions"><button className="icon-button" title="Edit card" onClick={()=>setEditWord(word)}><PenLine size={16}/></button><button className="icon-button" title="Delete card" onClick={()=>setDeleteTarget({kind:'word',id:word.id,name:word.word})}><Trash2 size={16}/></button></div></div>{expanded===word.id&&<div className="word-detail">{word.pronunciation&&<p className="pronunciation">{word.pronunciation}</p>}{word.examples?.length?word.examples.map((example,i)=><p key={i}>“{example}”</p>):<p className="muted">Add an example or a personal note using Edit card.</p>}{word.notes&&<p>{word.notes}</p>}<span className="muted small">{card.reps} reviews · {Math.round(card.stability*10)/10} days stability</span></div>}</div>;})}</div>:<Empty title={query?'No words found':'Every collection starts with a word'} body={query?'Try another word or translation.':'Create a set, add something you’re curious about, and let practice do the rest.'} action={!query&&<button className="button secondary" onClick={()=>selectedDeck?addCards(selectedDeck):go('create')}><Plus size={16}/> {selectedDeck?'Add cards':'Create a set'}</button>}/>}</div></>}
 {page==='sets'&&<><div className="deck-grid">{decks.map((deck,i)=><div className="managed-deck" key={deck.id}><DeckTile deck={deck} count={words.filter(w=>w.deckId===deck.id).length} index={i} onClick={()=>{setSelected(deck.id);go('learn');}}/><div className="deck-controls"><label><input type="checkbox" checked={deck.active} disabled={busy||decks.length===1} title={decks.length===1?'Your only set is always active for study':undefined} onChange={e=>run(async()=>{await owl.saveDeck({...deck,active:e.target.checked});})}/> Active for study</label><button className="icon-button" aria-label={`Options for ${deck.name}`} onClick={()=>setMenu(menu===deck.id?'':deck.id)}><MoreHorizontal size={19}/></button></div>{menu===deck.id&&<div className="deck-menu"><button onClick={()=>go('create',deck)}><PenLine size={15}/> Edit set</button><button onClick={()=>addCards(deck)}><Plus size={15}/> Add cards</button><button onClick={()=>run(async()=>{if(await owl.exportDeck(deck.id))notify('Set exported.');setMenu('');})}><Download size={15}/> Export CSV</button><button onClick={()=>run(async()=>{const result=await owl.publish(deck.id);notify(`Publication status: ${result.status}`);setMenu('');})}><Upload size={15}/> Publish to library</button><button onClick={()=>run(async()=>{await owl.unpublish(deck.id);notify('Set unpublished.');setMenu('');})}><CloudOff size={15}/> Unpublish</button><button className="danger" onClick={()=>{setDeleteTarget({kind:'deck',id:deck.id,name:deck.name});setMenu('');}}><Trash2 size={15}/> Delete set</button></div>}</div>)}<button className="new-deck-tile" onClick={()=>go('create')}><span><Plus size={24}/></span><strong>Something new to learn</strong><small>Create a set</small></button></div>{!decks.length&&<Empty title="A home for your discoveries" body="Build collections around your travels, conversations, books, or whatever makes you curious."/>}</>}
 {(page==='create'||page==='add')&&<CreateSet cardsOnly={page==='add'} key={page+(editDeck?.id??'new')} snapshot={snapshot} deck={editDeck} onSaved={deck=>{if(workspace.current!==snapshot.scopeRevision)return;setSelected(deck.id);if(page==='create'){returnPages.current=[];setPage('learn');}void reload();}} notify={notify}/>}{page==='profile'&&<Profile account={account} onChanged={reload} notify={notify}/>}{page==='settings'&&<Settings key={JSON.stringify(settings)} settings={settings} onChanged={reload} notify={notify}/>}{page==='help'&&<Help onCreate={()=>go('create')} onProfile={()=>go('profile')} onSettings={()=>go('settings')}/>}{page==='library'&&<Library onChanged={reload} notify={notify}/>}<footer className="page-footer"><Owl size={17}/><span>Made for curious minds.</span><span>OWL AI · WINDOWS</span></footer></div></main>
 {notice&&<div className="toast" role="status"><Check size={18}/><span>{notice}</span><button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={15}/></button></div>}{review&&<Review key={snapshot.scopeRevision} snapshot={snapshot} onClose={()=>{setReview(false);void reload();}} onChanged={reload}/>}{editWord&&<EditWord key={snapshot.scopeRevision+editWord.id} word={editWord} onClose={()=>setEditWord(null)} onSave={draft=>run(async()=>{await owl.editWord(editWord.id,draft);setEditWord(null);notify('Card updated.');})}/>}{deleteTarget&&<Modal title={`Delete ${deleteTarget.kind==='deck'?'set':'card'}?`} onClose={()=>setDeleteTarget(null)}><p>Delete <strong>{deleteTarget.name}</strong>{deleteTarget.kind==='deck'?' and all its local cards and review history':''}? This cannot be undone.</p>{deleteTarget.kind==='deck'&&<p className="muted small">If published, unpublish it first to remove the separate library copy.</p>}<div className="modal-actions"><button className="button secondary" onClick={()=>setDeleteTarget(null)}>Keep it</button><button className="button destructive" disabled={busy} onClick={()=>run(async()=>{if(deleteTarget.kind==='deck')await owl.deleteDeck(deleteTarget.id);else await owl.deleteWord(deleteTarget.id);setDeleteTarget(null);})}>Delete</button></div></Modal>}
 {!settings.onboardingComplete&&<Onboarding key={snapshot.scopeRevision} settings={settings} onSave={(native,learning)=>run(async()=>{await owl.saveSettings({nativeLanguage:native,learningLanguage:learning,onboardingComplete:true});})}/>}</div></WorkspaceBridgeProvider>;
}
function CollectionTile({deck,count,selected,onClick}:{deck:Deck;count:number;selected:boolean;onClick:()=>void}){return <button className="collection-mini" aria-pressed={selected} onClick={onClick}><span className="collection-name">{deck.name}</span><span className="collection-meta"><span>{count} {count===1?'card':'cards'}</span><span className="deck-languages">{deck.learningLanguage.split('-')[0].toUpperCase()} <ArrowRight size={10}/> {deck.nativeLanguage.toUpperCase()}</span></span></button>;}
function Stat({Icon,label,value,detail,color}:{Icon:typeof BookOpen;label:string;value:number;detail:string;color:string}){return <div className="stat-card"><div className={`stat-icon ${color}`}><Icon size={20}/></div><span>{label}</span><strong>{value}<small>{label==='Day streak'?'days':''}</small></strong><p>{detail}</p></div>;}
function DeckTile({deck,count,index,onClick,selected=false}:{deck:Deck;count:number;index:number;onClick:()=>void;selected?:boolean}){return <button className={`deck-tile tile-${index%4} ${selected?'selected':''}`} onClick={onClick}><div className="deck-tile-top"><div className="deck-icon"><BookOpen size={23}/></div><span className="deck-languages">{deck.learningLanguage.split('-')[0].toUpperCase()} <ArrowRight size={10}/> {deck.nativeLanguage.toUpperCase()}</span></div><h3>{deck.name}</h3><p>{deck.description||`${languageName(deck.learningLanguage)} · a little, every day`}</p><div className="deck-tile-bottom"><span>{count} cards</span><span className="tile-arrow"><ArrowRight size={16}/></span></div></button>;}
function EditWord({word,onClose,onSave}:{word:Word;onClose:()=>void;onSave:(draft:Draft)=>Promise<void>}){const [draft,setDraft]=useState<Draft>(word),[busy,setBusy]=useState(false);return <Modal title="A word worth remembering" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);await onSave(draft);setBusy(false);}}><label className="field">Word<input required value={draft.word} onChange={e=>setDraft({...draft,word:e.target.value})}/></label><label className="field">Translation<input required value={draft.translation} onChange={e=>setDraft({...draft,translation:e.target.value})}/></label><label className="field">Pronunciation<input value={draft.pronunciation??''} onChange={e=>setDraft({...draft,pronunciation:e.target.value})}/></label><label className="field">Examples · one per line<textarea rows={3} value={draft.examples?.join('\n')??''} onChange={e=>setDraft({...draft,examples:e.target.value.split('\n').filter(Boolean)})}/></label><label className="field">Personal notes<textarea rows={2} value={draft.notes??''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={busy}>Save card</button></div></form></Modal>;}
function Onboarding({settings,onSave}:{settings:Snapshot['settings'];onSave:(native:string,learning:string)=>Promise<void>}){const [native,setNative]=useState(settings.nativeLanguage),[learning,setLearning]=useState(settings.learningLanguage),[busy,setBusy]=useState(false);return <Modal title="Welcome to your next chapter." onClose={()=>{}}><div className="welcome-owl"><Owl size={75}/></div><p className="muted">A little curiosity, a few words, a daily moment to yourself. Let’s make this space yours.</p><div className="two-cols"><LanguageSelect label="I speak" value={native} onChange={setNative}/><LanguageSelect label="I want to learn" value={learning} onChange={setLearning}/></div><button className="button full" disabled={busy} onClick={async()=>{setBusy(true);await onSave(native,learning);setBusy(false);}}>Make room for discovery <ArrowRight size={17}/></button><p className="small muted center">No account needed to begin. Your words stay on your computer.</p></Modal>;}
