import { useState } from 'react';
import { ArrowRight,FileUp,PenLine,Sparkles,Clipboard,Plus,Trash2,Check,LoaderCircle } from 'lucide-react';
import type { Snapshot,Draft,Deck } from '../shared/types';
import { LanguageSelect,errorMessage } from './components';
export default function CreateSet({snapshot,deck,cardsOnly=false,onSaved,notify}:{snapshot:Snapshot;deck?:Deck;cardsOnly?:boolean;onSaved:(deck:Deck)=>void;notify:(message:string)=>void}){
 const [name,setName]=useState(deck?.name??''),[description,setDescription]=useState(deck?.description??''),[native,setNative]=useState(deck?.nativeLanguage??snapshot.settings.nativeLanguage),[learning,setLearning]=useState(deck?.learningLanguage??snapshot.settings.learningLanguage);
 const [method,setMethod]=useState<'manual'|'ai'|'paste'|'file'>('manual'),[rows,setRows]=useState<(Draft&{selected:boolean})[]>([]),[word,setWord]=useState(''),[translation,setTranslation]=useState(''),[text,setText]=useState(''),[mode,setMode]=useState<'auto'|'pairs'|'words'>('auto'),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const append=(drafts:Draft[])=>setRows(previous=>[...previous,...drafts.map(x=>({...x,selected:true}))]);
 const run=async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setError('');try{await fn();}catch(e){setError(errorMessage(e));}finally{setBusy('');}};
 const add=()=>{if(word.trim()&&translation.trim()){append([{word:word.trim(),translation:translation.trim()}]);setWord('');setTranslation('');}};
 async function save(){await run(cardsOnly?'Saving your cards':'Saving your set',async()=>{
  if(cardsOnly){
   if(!deck)throw new Error('Choose a set before adding cards.');
   const selected=rows.filter(x=>x.selected);
   if(!selected.length)throw new Error('Add at least one card to the preview.');
   if(selected.some(x=>!x.word.trim()||!x.translation.trim()))throw new Error('Complete the word and translation on every selected card.');
   const count=await window.owl.addWords(deck.id,selected.map(({selected,...row})=>row));
   notify(count?count+' cards added.':'These cards are already in your set.');onSaved(deck);
  }else{
   if(!name.trim())throw new Error('Give your set a name.');
   const saved=await window.owl.saveDeck({id:deck?.id,name,description,nativeLanguage:native,learningLanguage:learning});
   notify(deck?'Set updated.':'Your set is ready. Add your first cards whenever you like.');onSaved(saved);
  }
 });}
 return <div className="create-layout single-panel">{!cardsOnly&&<section className="panel"><div className="section-number">01 <span>MAKE IT YOURS</span></div><h2>{deck?'Edit your set':'A new collection of words'}</h2><p className="muted">Give your ideas a place to grow. All cards are saved on this computer.</p><label className="field">Set name<input autoFocus maxLength={100} placeholder="e.g. A little French, every day" value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Description <span className="optional">optional</span><input maxLength={500} placeholder="What would you like to learn?" value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="two-cols"><LanguageSelect label="I speak" value={native} onChange={setNative}/><LanguageSelect label="I'm learning" value={learning} onChange={setLearning}/></div><div className="local-note"><Check size={15}/> Yours to keep. Available offline.</div>{error&&<div className="error" role="alert">{error}</div>}<div className="save-bar"><span className="muted small">Add cards after creating your set.</span><button className="button" disabled={!!busy||!name.trim()} onClick={save}>Save set <ArrowRight size={17}/></button></div></section>}
 {cardsOnly&&<section className="panel"><div className="section-number">02 <span>ADD YOUR CARDS</span></div><h2>{deck?.name}</h2><p className="muted">Add words to this collection. Preview your cards before saving.</p><div className="method-grid">{([['manual',PenLine,'Write a card'],['ai',Sparkles,'AI translation'],['paste',Clipboard,'Paste text'],['file',FileUp,'Import a file']] as const).map(([id,Icon,label])=><button key={id} className={`method ${method===id?'selected':''}`} onClick={()=>setMethod(id)}><Icon size={21}/>{label}</button>)}</div>
 {(method==='manual'||method==='ai')&&<><div className="two-cols"><label className="field">Word or phrase<input value={word} onChange={e=>setWord(e.target.value)} placeholder="Something worth remembering" onKeyDown={e=>{if(e.key==='Enter'&&method==='manual')add();}}/></label>{method==='manual'&&<label className="field">Translation<input value={translation} onChange={e=>setTranslation(e.target.value)} placeholder="What does it mean?" onKeyDown={e=>{if(e.key==='Enter')add();}}/></label>}</div>{method==='manual'?<button className="button secondary" disabled={!word.trim()||!translation.trim()||!!busy} onClick={add}><Plus size={17}/> Add to preview</button>:<><p className="muted small">Uses your shared Premium subscription. Nothing is saved until you choose Save cards.</p><button className="button" disabled={!word.trim()||!!busy} onClick={()=>run('Translating',async()=>{append([await window.owl.translate(word,native,learning)]);setWord('');})}><Sparkles size={17}/> Translate with AI</button></>}</>}
 {(method==='paste'||method==='file')&&<><div className="segmented">{(['words','pairs','auto'] as const).map(m=><button className={mode===m?'selected':''} onClick={()=>setMode(m)} key={m}>{m==='words'?'Words':m==='pairs'?'Pairs':'Auto'}</button>)}</div>{method==='paste'?<><textarea value={text} onChange={e=>setText(e.target.value)} rows={6} placeholder={'hello — привет\nthank you — спасибо'}/><button className="button secondary" disabled={!text.trim()||!!busy} onClick={()=>run('Reading text',async()=>append(await window.owl.parse(text,mode)))}>Preview cards <ArrowRight size={16}/></button></>:<div className="drop-zone"><FileUp size={30}/><h3>Bring your words along</h3><p>TXT, CSV, TSV, PDF, or an image · up to 20 MB</p><button className="button secondary" disabled={!!busy} onClick={()=>run('Reading file · first OCR use downloads language data',async()=>{const file=await window.owl.importFile(mode);if(file){setText(file.text);append(file.drafts);}})}>Choose a file</button><span className="muted small">Files are processed on your computer.</span></div>}</>}
 {rows.length>0&&<div className="draft-area"><div className="section-line"><h3>Preview <span className="count">{rows.filter(x=>x.selected).length}</span></h3><button className="text-button" disabled={!!busy} onClick={()=>run('Translating missing words',async()=>{const updated=[...rows];for(let i=0;i<updated.length;i++)if(updated[i].selected&&!updated[i].translation.trim())updated[i]={...updated[i],...await window.owl.translate(updated[i].word,native,learning)};setRows(updated);})}><Sparkles size={14}/> Fill missing translations</button></div><div className="draft-list">{rows.map((row,index)=><div className="draft-row" key={index}><input type="checkbox" checked={row.selected} aria-label={`Include card ${index+1}`} onChange={e=>setRows(rows.map((x,i)=>i===index?{...x,selected:e.target.checked}:x))}/><input aria-label={`Word ${index+1}`} value={row.word} onChange={e=>setRows(rows.map((x,i)=>i===index?{...x,word:e.target.value}:x))}/><ArrowRight size={14}/><input aria-label={`Translation ${index+1}`} value={row.translation} placeholder="Translation" onChange={e=>setRows(rows.map((x,i)=>i===index?{...x,translation:e.target.value}:x))}/><button className="icon-button" aria-label="Remove draft" onClick={()=>setRows(rows.filter((_,i)=>i!==index))}><Trash2 size={15}/></button></div>)}</div></div>}
 {error&&<div className="error" role="alert">{error}</div>}{busy&&<p className="loading-line" role="status"><LoaderCircle className="spin" size={16}/>{busy}…</p>}<div className="save-bar"><span className="muted small">{rows.filter(x=>x.selected).length} new cards ready to save</span><button className="button" disabled={!!busy} onClick={save}>Save cards <ArrowRight size={17}/></button></div></section>}</div>;
}
