import { useOwl } from './WorkspaceBridge';
import { useState } from 'react';
import { Search,Download,Globe,BookOpen,LoaderCircle } from 'lucide-react';
import type { CatalogDeck } from '../shared/types';
import { Empty,errorMessage,Modal } from './components';
export default function Library({onChanged,notify}:{onChanged:()=>Promise<void>;notify:(message:string)=>void}){
 const owl=useOwl();
 const [query,setQuery]=useState(''),[decks,setDecks]=useState<CatalogDeck[]>([]),[searched,setSearched]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<CatalogDeck|null>(null);
 async function search(){setBusy(true);setError('');try{setDecks(await owl.catalog(query));setSearched(true);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <><div className="library-intro"><div><span className="eyebrow">A WORLD OF WORDS</span><h1>Find your next curiosity.</h1><p>Discover published sets and make them part of your daily practice.</p></div><Globe size={92} strokeWidth={1}/></div><form className="library-search" onSubmit={e=>{e.preventDefault();void search();}}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search topics, languages, or a little inspiration…"/><button className="button" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Search size={17}/>} Explore library</button></form>{error&&<p className="error" role="alert">{error}</p>}<div className="deck-grid">{decks.map(deck=><button key={deck.id} className="deck-tile library-deck" onClick={()=>setPreview(deck)}><div className="deck-icon"><BookOpen size={24}/></div><h3>{deck.title}</h3><p>{deck.description??'A new set of words to discover.'}</p><span className="muted small">{deck.word_count} cards <span className="tile-arrow">↗</span></span></button>)}</div>{!decks.length&&!busy&&<Empty title={searched?'No sets found':'Your next discovery starts here'} body={searched?'Try another topic or language.':'Sign in to browse the shared library. Imported sets are saved locally for offline study.'}/>}
 {preview&&<Modal title={preview.title} onClose={()=>setPreview(null)} wide><p className="muted">{preview.description}</p><div className="catalog-preview">{preview.cards.slice(0,40).map((card,i)=><div className="catalog-row" key={i}><strong>{card.word}</strong><span>{card.translations.join('; ')}</span></div>)}</div><div className="modal-actions"><span className="muted small">{preview.word_count} cards · saved to this computer</span><button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{await owl.importCatalog(preview);setPreview(null);await onChanged();notify('Set imported. Check your selected study languages in Settings.');}catch(e){setError(errorMessage(e));setPreview(null);}finally{setBusy(false);}}}><Download size={16}/> Add to my sets</button></div></Modal>}</>;
}
