import { useState } from 'react';
import { ShieldCheck,Monitor,Smartphone,ArrowRight,RefreshCw,LogOut,Crown,Link2,Check,Mail } from 'lucide-react';
import type { AccountState } from '../shared/types';
import { Modal,errorMessage } from './components';
export default function Profile({account,onChanged,notify}:{account:AccountState;onChanged:()=>Promise<void>;notify:(message:string)=>void}){
 const [register,setRegister]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[deleting,setDeleting]=useState(false);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await onChanged();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 const premium=['premium','trial','grace'].includes(account.entitlement?.status??'');
 return <div className="profile-layout"><section className="panel"><span className="eyebrow">YOUR OWL AI ACCOUNT</span><h2>{account.profile?'One account. Your learning space.':'A familiar space, on every screen.'}</h2><p className="muted">Your cards stay on this computer. Sign in to access the online library and your shared Premium subscription.</p>{error&&<p className="error" role="alert">{error}</p>}
 {account.profile?<><div className="profile-person"><div className="avatar large">{(account.profile.email??'O').charAt(0).toUpperCase()}</div><div><h3>{account.profile.email??account.profile.display_name??'Owl AI learner'}</h3><span className="muted small">Signed in securely</span></div><ShieldCheck className="accent" size={23}/></div><button className="button secondary" disabled={busy} onClick={()=>run(async()=>{await window.owl.logout();notify('Signed out. Your local cards are safe.');})}><LogOut size={16}/> Sign out</button><div className="danger-zone"><h3>Delete account</h3><p className="muted small">Deletes your server account and shared access. Local cards stay here. Apple billing must be canceled separately.</p><button className="text-button danger" disabled={busy} onClick={()=>setDeleting(true)}>Delete my account</button></div></>:<form onSubmit={e=>{e.preventDefault();void run(async()=>{await window.owl.login(email,password,register?confirmation:undefined);setPassword('');setConfirmation('');notify('Welcome to your Owl AI account.');});}}><div className="segmented"><button type="button" className={!register?'selected':''} onClick={()=>setRegister(false)}>Sign in</button><button type="button" className={register?'selected':''} onClick={()=>setRegister(true)}>Create account</button></div><label className="field">Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label className="field">Password<input type="password" autoComplete={register?'new-password':'current-password'} minLength={register?8:undefined} required value={password} onChange={e=>setPassword(e.target.value)} placeholder={register?'At least 8 characters':'Your password'}/></label>{register&&<label className="field">Confirm password<input type="password" autoComplete="new-password" required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>}<button className="button full" disabled={busy}>{busy?'Connecting…':register?'Create your account':'Welcome back'}<ArrowRight size={17}/></button><p className="small muted">You can always create and review local cards without an account.</p></form>}</section>
 <section className="premium-panel"><div className="premium-mark"><Crown size={25}/><span>OWL AI PREMIUM</span></div><h1>One subscription.<br/>More places to grow.</h1><p>Your iPhone subscription comes with you to Windows.</p><div className="devices"><Smartphone size={42}/><Link2 size={23}/><Monitor size={52}/></div><div className="premium-status"><span>{premium?'Premium is active':account.entitlement?account.entitlement.status.replace(/_/g,' '):'Connect your subscription'}</span>{premium&&<Check size={19}/>}</div>{account.entitlement?.expires_at&&<p className="small">{account.entitlement.auto_renew?'Current period ends':'Access until'} {new Date(account.entitlement.expires_at).toLocaleDateString()}</p>}<ol className="steps"><li>Open Owl AI on iPhone and sign in to this account.</li><li>Link your verified Apple purchase in Profile.</li><li>Refresh here. Your Premium works on both devices.</li></ol><button className="button premium-button" disabled={!account.profile||busy} onClick={()=>run(async()=>{await window.owl.refreshEntitlement();notify('Subscription status updated.');})}><RefreshCw size={16}/> Refresh subscription</button><button className="premium-link" onClick={()=>window.owl.openSubscriptionManagement().catch(e=>setError(errorMessage(e)))}>Manage Apple subscription <ArrowRight size={14}/></button><p className="small premium-note">No second purchase needed. Card synchronization is not included yet.</p></section>
 {deleting&&<Modal title="Delete your Owl AI account?" onClose={()=>!busy&&setDeleting(false)}><p>This removes your server account and shared subscription access. A linked purchase cannot be automatically attached to a new account.</p><p>Your local cards remain. Deleting your account does not cancel Apple billing.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setDeleting(false)}>Keep account</button><button className="button destructive" disabled={busy} onClick={()=>run(async()=>{await window.owl.deleteAccount();setDeleting(false);notify('Account deleted. Your local cards remain.');})}>Delete account</button></div></Modal>}</div>;
}
