import { useOwl } from './WorkspaceBridge';
import { useEffect,useState } from 'react';
import { ShieldCheck,Monitor,Smartphone,ArrowRight,LogOut,Crown,Link2,Check } from 'lucide-react';
import type { AccountState } from '../shared/types';
import { Modal,errorMessage } from './components';
export default function Profile({account,onChanged,notify}:{account:AccountState;onChanged:()=>Promise<void>;notify:(message:string)=>void}){
 const owl=useOwl();
 // Cancellation is unscoped: only leaving the profile cancels, not refreshing its IPC bridge.
 useEffect(()=>()=>{void owl.cancelGoogleLogin().catch(()=>{});},[]);
 const [googlePending,setGooglePending]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[deleting,setDeleting]=useState(false);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(errorMessage(e));}finally{try{await onChanged();}catch(e){setError(errorMessage(e));}setBusy(false);}};
 const premium=['premium','trial','grace'].includes(account.entitlement?.status??'');
 const sync=account.sync;
 const syncLabel=sync?.state==='syncing'?'Syncing your cards…':sync?.state==='synced'?'Your cards are synced':sync?.state==='conflict'?'Some changes need attention':sync?.state==='error'?'Sync could not finish':'Ready to sync';
 return <div className="profile-layout"><section className="panel"><span className="eyebrow">YOUR OWL AI ACCOUNT</span><h2>{account.profile?'One account. Your learning space.':'Your iPhone account, on Windows.'}</h2><p className="muted">{account.profile?'Your collections, cards, and review schedule sync with this same account on iPhone. Your signed-out cards stay in a separate space on this computer.':'First create or open your account in Owl AI on iPhone. Then sign in here using the same email or Google account. Windows does not create new accounts.'}</p>{error&&<p className="error" role="alert">{error}</p>}
 {account.profile?<><div className="profile-person"><div className="avatar large">{(account.profile.email??'O').charAt(0).toUpperCase()}</div><div><h3>{account.profile.email??account.profile.display_name??'Owl AI learner'}</h3><span className="muted small">Your private account workspace</span></div><ShieldCheck className="accent" size={23}/></div>
 <section aria-label="Account synchronization"><h3>{syncLabel}</h3><p className="small muted" role="status">{sync?.message??(sync?.lastSyncedAt?`Last synced ${new Date(sync.lastSyncedAt).toLocaleString()}.`:'Changes sync automatically while you are online. Only data belonging to this account is included.')}</p><p className="small muted">Signed-out cards are never uploaded automatically. Sign out to return to them.</p></section>
 <button className="button secondary" disabled={busy} onClick={()=>run(async()=>{await owl.logout();notify('Signed out. Returned to your separate local workspace.');})}><LogOut size={16}/> Sign out</button><div className="danger-zone"><h3>Delete account</h3><p className="muted small">Deletes your server account, synced data, and shared access. Your separate signed-out workspace is preserved. Apple billing must be canceled separately.</p><button className="text-button danger" disabled={busy} onClick={()=>setDeleting(true)}>Delete my account</button></div></>:<form onSubmit={e=>{e.preventDefault();void run(async()=>{await owl.login(email,password);setPassword('');notify('Welcome to your Owl AI account.');});}}><button type="button" className="button secondary full google-sign-in" disabled={busy} onClick={()=>run(async()=>{setGooglePending(true);try{const result=await owl.loginGoogle();if(result)notify('Welcome to your Owl AI account.');}finally{setGooglePending(false);}})}><span aria-hidden="true" className="google-letter">G</span> Continue with Google</button>{googlePending&&<div className="google-wait"><p className="small muted">Continue in your browser with the Google account you use in Owl AI on iPhone.</p><button type="button" className="text-button" onClick={()=>owl.cancelGoogleLogin().catch(e=>setError(errorMessage(e)))}>Cancel Google sign-in</button></div>}<p className="small muted center">or sign in with email</p><label className="field">Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label className="field">Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/></label><button className="button full" disabled={busy}>{busy?'Connecting…':'Sign in'}<ArrowRight size={17}/></button><p className="small muted">You can still create and review local cards without signing in. These cards are kept separate from your account.</p></form>}</section>
 {account.testMode?<section className="premium-panel"><div className="premium-mark"><Check size={25}/><span>Test mode</span></div><h1>All learning features are available.</h1><p>Word limits and AI quotas are lifted while test mode is active. Sign in to use online features.</p></section>:<section className="premium-panel"><div className="premium-mark"><Crown size={25}/><span>OWL AI PREMIUM</span></div><h1>One subscription.<br/>More places to grow.</h1><p>Your iPhone subscription comes with you to Windows.</p><div className="devices"><Smartphone size={42}/><Link2 size={23}/><Monitor size={52}/></div><div className="premium-status"><span>{premium?'Premium is active':account.entitlement?account.entitlement.status.replace(/_/g,' '):'Connect your subscription'}</span>{premium&&<Check size={19}/>}</div>{account.entitlement?.expires_at&&<p className="small">{account.entitlement.auto_renew?'Current period ends':'Access until'} {new Date(account.entitlement.expires_at).toLocaleDateString()}</p>}<ol className="steps"><li>Open Owl AI on iPhone and sign in to this account.</li><li>Link your verified Apple purchase in Profile.</li><li>Your Premium updates automatically on both devices.</li></ol><p className="small premium-note">No second purchase needed. Use the same account on both devices for your cards and Premium.</p></section>}
 {deleting&&<Modal title="Delete your Owl AI account?" onClose={()=>!busy&&setDeleting(false)}><p>This removes your server account, synced data, and shared subscription access. A linked purchase cannot be automatically attached to a new account.</p><p>Your separate signed-out workspace is preserved. Deleting your account does not cancel Apple billing.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setDeleting(false)}>Keep account</button><button className="button destructive" disabled={busy} onClick={()=>run(async()=>{await owl.deleteAccount();setDeleting(false);notify('Account deleted. Returned to your separate local workspace.');})}>Delete account</button></div></Modal>}</div>;
}
