import { useOwl } from './WorkspaceBridge';
import { useEffect,useState,useCallback,useRef } from 'react';
import { ArrowRight,Check,RotateCcw } from 'lucide-react';
import type { Snapshot,Word } from '../shared/types';
import { Modal,Speak,errorMessage } from './components';
function interval(date:string){const minutes=Math.max(1,Math.round((new Date(date).getTime()-Date.now())/60000));return minutes<60?`${minutes}m`:minutes<1440?`${Math.round(minutes/60)}h`:`${Math.round(minutes/1440)}d`;}
export default function Review({snapshot,deckId,onClose,onChanged}:{snapshot:Snapshot;deckId?:string;onClose:()=>void;onChanged:()=>Promise<void>}){
 const owl=useOwl();
 const [queue,setQueue]=useState<Word[]>([]),[revealed,setRevealed]=useState(false),[previews,setPreviews]=useState<Record<number,string>>({}),[busy,setBusy]=useState(true),[error,setError]=useState(''),[completed,setCompleted]=useState(0),[loaded,setLoaded]=useState(false);const grading=useRef(false),attempt=useRef(crypto.randomUUID());const word=queue[0],reverse=snapshot.settings.direction==='reverse';
 useEffect(()=>{void owl.reviewSession(true).catch(()=>{});return()=>{void owl.reviewSession(false).catch(()=>{});};},[owl]);
 useEffect(()=>{if(loaded)void owl.reviewSession(queue.length>0).catch(()=>{});},[loaded,queue.length,owl]);
 const load=useCallback(async()=>{const rows=await owl.queue(deckId);setQueue(rows);setPreviews(rows[0]?await owl.previews(rows[0].id):{});setLoaded(true);},[deckId,owl]);
 useEffect(()=>{load().catch(e=>setError(errorMessage(e))).finally(()=>setBusy(false));},[load]);
 const grade=useCallback(async(rating:number)=>{if(!word||!revealed||grading.current)return;grading.current=true;setBusy(true);try{await owl.review(word.id,rating,attempt.current);attempt.current=crypto.randomUUID();setCompleted(x=>x+1);setRevealed(false);await load();await onChanged();}catch(e){setError(errorMessage(e));}finally{grading.current=false;setBusy(false);}},[word,revealed,load,onChanged,owl]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select'))return;if(e.code==='Space'){e.preventDefault();setRevealed(true);}else if(['1','2','3','4'].includes(e.key)){e.preventDefault();void grade(Number(e.key));}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[grade]);
 const deck=snapshot.decks.find(x=>x.id===word?.deckId);
 return <Modal title="A moment to remember" onClose={onClose} wide><div className="review-meta"><span>{deck?.name??'Daily practice'}</span><span>{completed} reviewed · {queue.length} ready</span></div><div className="progress-track"><div style={{width:`${completed/(completed+queue.length||1)*100}%`}}/></div>{error&&<p className="error" role="alert">{error}</p>}
 {word?<><div className="review-card"><span className="eyebrow">{reverse?'RECALL THE WORD':'WHAT DOES THIS MEAN?'}</span><h1>{reverse?word.translation:word.word}</h1>{!reverse&&word.pronunciation&&<p className="pronunciation">{word.pronunciation}</p>}<Speak word={reverse?word.translation:word.word} language={reverse?(word.nativeLanguage??deck?.nativeLanguage??snapshot.settings.nativeLanguage):(word.learningLanguage??deck?.learningLanguage??snapshot.settings.learningLanguage)} onError={setError}/>{revealed?<div className="answer"><span className="eyebrow">{reverse?'WORD':'TRANSLATION'}</span><h2>{reverse?word.word:word.translation}</h2>{word.examples?.[0]&&<p>“{word.examples[0]}”</p>}{word.notes&&<p className="muted">{word.notes}</p>}</div>:<p className="review-prompt">Take a breath. Try to remember before you reveal.</p>}</div>{!revealed?<button className="button full" disabled={busy} onClick={()=>setRevealed(true)}>Show answer <kbd>Space</kbd></button>:<div className="grade-grid">{['Again','Hard','Good','Easy'].map((label,i)=><button key={label} className={`grade grade-${i+1}`} disabled={busy} onClick={()=>grade(i+1)}><span>{label} <kbd>{i+1}</kbd></span><small>{previews[i+1]?interval(previews[i+1]):'—'}</small></button>)}</div>}<p className="review-footer">Small repetitions build lasting memories.</p></>:loaded?<div className="review-done"><span className="done-icon"><Check size={34}/></span><h1>{completed?'Well done. Make it a habit.':'You’re all caught up.'}</h1><p>{completed?`You practiced ${completed} cards. Your next reviews are scheduled.`:'No more cards are ready right now. New cards follow your daily goal and selected languages.'}</p><button className="button" onClick={onClose}>Back to your space <ArrowRight size={16}/></button><button className="text-button" onClick={()=>load().catch(e=>setError(errorMessage(e)))}><RotateCcw size={14}/> Check for due cards</button></div>:<p className="muted">Preparing your cards…</p>}</Modal>;
}
