import { useState } from 'react';
import { Bell,Database,Download,Upload,Palette,SlidersHorizontal } from 'lucide-react';
import type { Settings as AppSettings } from '../shared/types';
import { LanguageSelect,errorMessage } from './components';
export default function Settings({settings,onChanged,notify}:{settings:AppSettings;onChanged:()=>Promise<void>;notify:(message:string)=>void}){
 const [values,setValues]=useState(settings),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const patch=(value:Partial<AppSettings>)=>setValues(x=>({...x,...value}));
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await onChanged();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 return <div className="settings-grid"><section className="panel"><div className="panel-title"><SlidersHorizontal size={20}/><h2>Your learning rhythm</h2></div><div className="two-cols"><LanguageSelect label="I speak" value={values.nativeLanguage} onChange={x=>patch({nativeLanguage:x})}/><LanguageSelect label="I'm learning" value={values.learningLanguage} onChange={x=>patch({learningLanguage:x})}/></div><label className="field">New words per study day<input type="number" min={0} max={200} value={values.dailyGoal} onChange={e=>patch({dailyGoal:Number(e.target.value)})}/></label><label className="field">Review direction<select value={values.direction} onChange={e=>patch({direction:e.target.value as AppSettings['direction']})}><option value="forward">Learning language → native language</option><option value="reverse">Native language → learning language</option></select></label><p className="muted small">Each direction has its own review history. Only active sets matching your selected languages enter the queue.</p><label className="field">Study day starts at<input type="time" value={`${Math.floor(values.dayStart/60).toString().padStart(2,'0')}:${(values.dayStart%60).toString().padStart(2,'0')}`} onChange={e=>{const [h,m]=e.target.value.split(':').map(Number);patch({dayStart:h*60+m});}}/></label><label className="field">FSRS desired retention · {Math.round(values.retention*100)}%<input type="range" min={70} max={97} value={Math.round(values.retention*100)} onChange={e=>patch({retention:Number(e.target.value)/100})}/></label></section>
 <div className="settings-stack"><section className="panel"><div className="panel-title"><Palette size={20}/><h2>Make yourself at home</h2></div><label className="field">Appearance<select aria-label="Appearance" value={values.theme} onChange={e=>patch({theme:e.target.value as AppSettings['theme']})}><option value="light">Light</option><option value="dark">Dark</option><option value="system">Follow Windows</option></select></label><div className="swatches">{(['indigo','teal','rose'] as const).map(accent=><button key={accent} title={accent} aria-label={`${accent} accent`} aria-pressed={values.accent===accent} className={`swatch ${accent} ${values.accent===accent?'selected':''}`} onClick={()=>patch({accent})}/>)}</div></section>
 <section className="panel"><div className="panel-title"><Bell size={20}/><h2>A gentle nudge</h2></div><label className="toggle-row"><span>Study reminders</span><input type="checkbox" checked={values.reminders} onChange={e=>patch({reminders:e.target.checked})}/></label>{values.reminders&&<label className="field">Remind me at<input type="time" value={values.reminderTime} onChange={e=>patch({reminderTime:e.target.value})}/></label>}<label className="toggle-row"><span>Keep running in the system tray</span><input type="checkbox" checked={values.keepInTray} onChange={e=>patch({keepInTray:e.target.checked})}/></label><label className="toggle-row"><span>Open when Windows starts</span><input type="checkbox" checked={values.launchAtLogin} onChange={e=>patch({launchAtLogin:e.target.checked})}/></label><p className="muted small">Reminders need Owl AI running. Keep it in the tray to receive them after closing the window.</p></section></div>
 <section className="panel"><div className="panel-title"><Database size={20}/><h2>Your data, in your hands</h2></div><p className="muted">Back up all sets and review progress to a local file. Account credentials are never included.</p><div className="button-row"><button className="button secondary" disabled={busy} onClick={()=>run(async()=>{if(await window.owl.backup())notify('Backup saved.');})}><Download size={16}/> Save backup</button><button className="button secondary" disabled={busy} onClick={()=>run(async()=>{if(await window.owl.restore())notify('Backup restored.');})}><Upload size={16}/> Restore backup</button></div></section>
{error&&<div className="error" role="alert">{error}</div>}<div className="settings-save"><span className="muted">Changes apply when you save.</span><button className="button" disabled={busy} onClick={()=>run(async()=>{await window.owl.saveSettings(values);notify('Settings saved.');})}>{busy?'Saving…':'Save preferences'}</button></div></div>;
}
