import { useEffect,useState } from 'react';
import TimeField from './TimeField';
import { Bell,Database,Download,Upload,Palette,SlidersHorizontal,Sun,Moon,Monitor,Check } from 'lucide-react';
import type { Settings as AppSettings } from '../shared/types';
import { LanguageSelect,errorMessage } from './components';
export default function Settings({settings,onChanged,notify}:{settings:AppSettings;onChanged:()=>Promise<void>;notify:(message:string)=>void}){
 const [values,setValues]=useState(settings),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [hour12,setHour12]=useState(()=>!!new Intl.DateTimeFormat(undefined,{hour:'numeric'}).resolvedOptions().hour12);
 useEffect(()=>{let active=true;const refresh=()=>{void window.owl.systemTimeFormat().then(format=>{if(active)setHour12(format.hour12);}).catch(()=>{});};refresh();window.addEventListener('focus',refresh);return()=>{active=false;window.removeEventListener('focus',refresh);};},[]);
 const patch=(value:Partial<AppSettings>)=>setValues(x=>({...x,...value}));
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await onChanged();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 return <div className="settings-grid"><section className="panel"><div className="panel-title"><SlidersHorizontal size={20}/><h2>Your learning rhythm</h2></div><div className="two-cols"><LanguageSelect label="I speak" value={values.nativeLanguage} onChange={x=>patch({nativeLanguage:x})}/><LanguageSelect label="I'm learning" value={values.learningLanguage} onChange={x=>patch({learningLanguage:x})}/></div><label className="field">New words per study day<input type="number" min={0} max={200} value={values.dailyGoal} onChange={e=>patch({dailyGoal:Number(e.target.value)})}/></label><label className="field">Review direction<select value={values.direction} onChange={e=>patch({direction:e.target.value as AppSettings['direction']})}><option value="forward">Learning language → native language</option><option value="reverse">Native language → learning language</option></select></label><p className="muted small">Each direction has its own review history. Only active sets matching your selected languages enter the queue.</p><label className="field">Study day starts at<input type="time" value={`${Math.floor(values.dayStart/60).toString().padStart(2,'0')}:${(values.dayStart%60).toString().padStart(2,'0')}`} onChange={e=>{const [h,m]=e.target.value.split(':').map(Number);patch({dayStart:h*60+m});}}/></label><label className="field">FSRS desired retention · {Math.round(values.retention*100)}%<input type="range" min={70} max={97} value={Math.round(values.retention*100)} onChange={e=>patch({retention:Number(e.target.value)/100})}/></label></section>
 <div className="settings-stack"><section className="panel"><div className="panel-title"><Palette size={20}/><h2>Make yourself at home</h2></div><div className="appearance-options" role="group" aria-label="Appearance">{([['light',Sun,'Light','Bright & clear'],['dark',Moon,'Dark','Soft graphite'],['system',Monitor,'System','Follow Windows']] as const).map(([theme,Icon,label,description])=><button type="button" key={theme} className={`appearance-card appearance-${theme}`} aria-label={label} aria-pressed={values.theme===theme} onClick={()=>patch({theme})}><span className="appearance-preview" aria-hidden="true"><Icon size={22}/>{values.theme===theme&&<Check className="appearance-check" size={14}/>}</span><strong>{label}</strong><small>{description}</small></button>)}</div><p className="accent-label">Light accent</p><div className="swatches" role="group" aria-label="Light accent">{(['indigo','teal','rose'] as const).map(accent=><button key={accent} title={accent} aria-label={`${accent} accent`} aria-pressed={values.accent===accent} className={`swatch ${accent} ${values.accent===accent?'selected':''}`} onClick={()=>patch({accent})}/>)}</div><p className="accent-label">Dark accent</p><div className="dark-accent-options" role="group" aria-label="Dark accent">{([['teal','Teal'],['indigo','Blue'],['rose','Rose']] as const).map(([accent,label])=><button type="button" key={accent} className={`dark-accent-choice dark-accent-${accent}`} aria-label={`${label} dark accent`} aria-pressed={values.darkAccent===accent} onClick={()=>patch({darkAccent:accent})}><span aria-hidden="true"/>{label}{values.darkAccent===accent&&<Check size={13}/>}</button>)}</div><p className="muted small">Choose a separate accent for each theme. Save preferences to apply your choices.</p></section>
 <section className="panel"><div className="panel-title"><Bell size={20}/><h2>A gentle nudge</h2></div><label className="toggle-row"><span>Study reminders</span><input type="checkbox" checked={values.reminders} onChange={e=>patch({reminders:e.target.checked})}/></label>{values.reminders&&<div className="reminder-window"><TimeField label="Start reminder time" value={values.reminderStart} hour12={hour12} onChange={reminderStart=>patch({reminderStart})}/><TimeField label="End reminder time" value={values.reminderEnd} hour12={hour12} onChange={reminderEnd=>patch({reminderEnd})}/><label className="field">Reminders per day<input type="number" min={1} max={100} step={1} value={values.reminderCount} onChange={e=>patch({reminderCount:Number(e.target.value)})}/></label><p className="muted small">Up to {values.reminderCount} reminders, evenly spaced within this period, only while cards are ready. The end time is not included. An earlier end time means the next day.</p></div>}<label className="toggle-row"><span>Keep running in the system tray</span><input type="checkbox" checked={values.keepInTray} onChange={e=>patch({keepInTray:e.target.checked})}/></label><label className="toggle-row"><span>Open when Windows starts</span><input type="checkbox" checked={values.launchAtLogin} onChange={e=>patch({launchAtLogin:e.target.checked})}/></label><p className="muted small">Reminders need Owl AI running. Keep it in the tray to receive them after closing the window.</p></section></div>
 <section className="panel"><div className="panel-title"><Database size={20}/><h2>Your data, in your hands</h2></div><p className="muted">Back up all sets and review progress to a local file. Account credentials are never included.</p><div className="button-row"><button className="button secondary" disabled={busy} onClick={()=>run(async()=>{if(await window.owl.backup())notify('Backup saved.');})}><Download size={16}/> Save backup</button><button className="button secondary" disabled={busy} onClick={()=>run(async()=>{if(await window.owl.restore())notify('Backup restored.');})}><Upload size={16}/> Restore backup</button></div></section>
{error&&<div className="error" role="alert">{error}</div>}<div className="settings-save"><span className="muted">Changes apply when you save.</span><button className="button" disabled={busy} onClick={()=>run(async()=>{await window.owl.saveSettings(values);notify('Settings saved.');})}>{busy?'Saving…':'Save preferences'}</button></div></div>;
}
